FROM ubuntu:24.04@sha256:cdb5fd928fced577cfecf12c8966e830fcdf42ee481fb0b91904eeddc2fe5eff

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc=4:13.2.0-7ubuntu1 \
    clang=1:18.0-59~exp2 \
    libclang-rt-18-dev=1:18.1.3-1ubuntu1 \
    lld=1:18.0-59~exp2 \
    llvm=1:18.0-59~exp2 \
    binutils=2.42-4ubuntu2.10 \
    libc6-dev=2.39-0ubuntu8.7 \
    && rm -rf /var/lib/apt/lists/*
