name: "Golden: ARM MTE"

# actions/checkout v7.0.1: 3d3c42e5aac5ba805825da76410c181273ba90b1
# actions/upload-artifact v7.0.1: 043fb46d1a93c77aae656e7c1c64a875d1fc6a0a

permissions:
  contents: read

on:
  workflow_dispatch:

env:
  TOOLCHAIN: ghcr.io/${{ github.repository }}/toolchain-

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Build binaries
        run: |
          docker run --rm \
            -v "$PWD:/workspace" -w /workspace \
            ${{ env.TOOLCHAIN }}android-ndk-r27c:v1 \
            sh test/e2e/elf/arm-mte/build.sh /opt/android-ndk
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: arm-mte-binaries
          path: binaries/
